### ISSUE TITLE
自定义页面可以吗

### ISSUE THREAD

**Issue by JDevFrame** [ikeq/hexo-theme-inside#101]
我看了 https://blog.oniuo.com/theme-inside 里面的内容，发现可以自定义的地方不是很多，比如我想 在列表 
![image](https://user-images.githubusercontent.com/45105543/60338754-68665280-99d9-11e9-80f8-c68742e5877e.png) 
自定义一些东西，我改哪里可以啊

**Comment by ike-c** [comment]
尚不支持

**Comment by ike-c** [comment]
有计划支持下阅读数统计什么的

**Comment by JDevFrame** [comment]
好的，我先研究研究你的源码，看看怎么改





**来自GitHub小程序客户端：**

![image](https://user-images.githubusercontent.com/8692455/51429898-b159f400-1c4e-11e9-91a1-59cd1fab5042.png)

**Comment by ike-c** [comment]
这是打了个广告？
