### ISSUE TITLE
你好，请问可以增加一个本地图片的设置吗

### ISSUE THREAD

**Issue by NEUQ-Luer** [ikeq/hexo-theme-inside#111]
首先，非常感谢你提供了如此优秀的Hexo主题。

我在使用过程中，想要自定义文章的图片本地路径，但是好像你主题的设置会自动按照CDN的方式加上前后缀，请问想要贴上本地图片应怎样修改。

**Comment by ikeq** [comment]
在 assets 那里配成本地路径的前缀不行吗

**Comment by NEUQ-Luer** [comment]
> 在 assets 那里配成本地路径的前缀不行吗

比如我的md图片为xx.gif
assets:
  prefix: /img/
  suffix: ''
后缀留空，但是实际链接却是/img//.cf//xx.gif
不知道为什么会加上一个域名后缀

**Comment by NEUQ-Luer** [comment]
Clean之后问题解决，再次感谢
