### ISSUE TITLE
关于highlight在暗背景下选中代码段明显不明显问题

### ISSUE THREAD

**Issue by Patrick-Jun** [ikeq/hexo-theme-inside#112]
- 个人偏好代码段暗背景，使用了google dark，之后发现当选中代码段进行复制时，选中区也是暗色，与背景色区分不明显，不太容易看出哪块选中了。

- 于是我试了试Highlighting Palette文章提供的大部分暗背景色，只发现Seti Ui区分度较友好。通过拾色器，我发现选中色并不没有在highlight中定义。

- 我想过，可能是浏览器默认选中色和背景色有重叠，于是我通过css设置::selection设置选中文字颜色，也是无效的。

**Comment by ikeq** [comment]
Highlighting Palette 里提供的色值是我直接拿的 github 上的，按照这个 base16 的规范，有些色值确实不合理，我也懒得细究，所以提供了完整的颜色配置，highlight 数组的第三个色值是 Selection Background，你自己改亮一点。
