### ISSUE TITLE
TOC随动失效

### ISSUE THREAD

**Issue by blackawn** [ikeq/hexo-theme-inside#116]
2.4.0版本里的`TOC`随动似乎失效了
![Snipaste_2019-08-14_01-17-25](https://user-images.githubusercontent.com/49859450/62962525-aefcf880-be31-11e9-8da0-a893f7ff7f6b.png)

**Comment by blackawn** [comment]
补充 :
1.点击非`focus`区域不会像之前的版本那样`TOC`会关闭
2.弹出`TOC`时悬浮的小菜单里的`搜索`按钮会消失

**Comment by ikeq** [comment]
啊，确实不太好看，不过搜索是故意消失的，弹层覆盖太多不好看

**Comment by ikeq** [comment]
滚动高亮好了，但 toc 开启时的那个蒙层不加了吧，这样在看文章的时候，也可以保持目录开启，特别是桌面端，而移动端手势划动也很方便~
