### ISSUE TITLE
希望可以在页面跳转时添加进度条功能

### ISSUE THREAD

**Issue by MoeCasts** [ikeq/hexo-theme-inside#117]
首次加载新页面时延迟较长，会让人误以为没跳转，添加个进度条可以知道正在跳转。

**Comment by ikeq** [comment]
任何网络请求，右下角的按钮就会转呀

**Comment by MoeCasts** [comment]
@ ikeq 好吧，有点没太注意。不过还是建议加进度条功能，那样比较容易让人知道。
