### ISSUE TITLE
header指向web链接，会导致内容页该header无法展示

### ISSUE THREAD

**Issue by spaco** [ikeq/hexo-theme-inside#121]
代码分支：最新master分支

文章内容如下
```bash
# Header1
## Header2
### [Header3Link](https://zh.wikipedia.org)
Content
```

内容页展示如下图：
![image](https://user-images.githubusercontent.com/24441899/63680983-64af4a80-c827-11e9-9a90-7eae6107bc69.png)
右侧列表如下图：
![image](https://user-images.githubusercontent.com/24441899/63681022-7a247480-c827-11e9-8835-6d7f54d5ddbb.png)

**Comment by ikeq** [comment]
Fixed [2.4.0](https://github.com/ikeq/hexo-theme-inside/releases/tag/2.4.0)
