### ISSUE TITLE
请问如何设置封面

### ISSUE THREAD

**Issue by MLLR-L** [ikeq/hexo-theme-inside#122]
首先感谢作者能做出这么棒的作品出来让大家使用，然后声明一下我是小白，如果问题有冒犯到请多有谅解。
问题：想请问下博主页面的封面是怎么做出来的呢？就好像博主的这一篇:https://blog.oniuo.com/post/highlighting-palette
我觉得这样放封面超酷的里外都能看到，图片也能点击链接，可是我做不到，找过网上都是教用插件，插件可以放但是我认为没有博主的好
所以这里想请教下博主，感谢！

**Comment by ikeq** [comment]
https://blog.oniuo.com/theme-inside/docs/front-matter#适用于-post
