### ISSUE TITLE
当给一篇文章贴多个分类的时候会出现问题

### ISSUE THREAD

**Issue by MLLR-L** [ikeq/hexo-theme-inside#123]
刚刚我在尝试给一篇文章贴多个分类的时候会出现重复且点两个标签是没用的显示的页面都是这个，希望博主可以了解一下，谢谢。
我是在hexo admin页面上修改的，也不知道是不是这个原因出现了这个问题
我

在附件中添加了出现这种情况的图片
![无标题](https://user-images.githubusercontent.com/52274334/63881655-ee673f80-ca02-11e9-9cff-29c41eddf137.png)

**Comment by ikeq** [comment]
不支持多分类，我觉得 一层分类 + tag 就很好啊~
