### ISSUE TITLE
Post support subdir

### ISSUE THREAD

**Issue by LouisozZ** [ikeq/hexo-theme-inside#126]
现有 `public/post/linux内核/内核同步方法/index.html` ，但是在 home 页面中点击相应文章标题，但是却显示 404 页面，页面提示信息为 无法定位到 `/post/linux内核/内核同步方法` 。文件组织结构未改变的情况下，更换官方默认主题是没有问题，文章能够定位到。

**Comment by LouisozZ** [comment]
此外还有一个问题，一般文章内跳转的时候 markdown 里面会写 \[display\]\(#锚点\)，使用 inside 主题的时候，如果点击这样的锚点，跳转到的是 `/#锚点`，而非是在当前文章的页面内进行页内跳转

**Comment by ikeq** [comment]
你这个 html 是自定义的文件，也就是说不是 hexo post，所以应该不会有路由才对，不知 "home 页面中点击相应文章标题" 是如何操作的，配在 menu 里？

**Comment by ikeq** [comment]
@LouisozZ 锚点跳转的我处理一下，多谢反馈

**Comment by LouisozZ** [comment]
不是自定义文件，文件结构为`source/_posts/linux内核/内核同步方法.md`，如果使用 hexo new ，新创建的文章在 `source/_posts/new_page.md`，我是将文章在资源文件夹中就分类了，然后手动在文章中添加
```
---
title: linux内核设计与实现/第10章内核同步方法
date: 2019-08-29 11:10:54
tags:
permalink: linux内核设计与实现/第10章内核同步方法
---
```
然后由命令 `hexo g` 生成的 index.html

**Comment by LouisozZ** [comment]
文件结构的路劲名我写的时候省略了，实际的路劲和 title 值是对应的。
对了，我是直接clone 的，不是下载的 release 版本

**Comment by ikeq** [comment]
post 路径是这样 `_post/linux内核/内核同步方法.md`？

**Comment by ikeq** [comment]
`_posts` 下面分了个子目录啊，这个确实没碰到过，我研究下，多谢反馈~

**Comment by LouisozZ** [comment]
对，添加了一个子目录，我是想方便管理。
--source
 |--_post
&nbsp;&nbsp;|--subdir1
 &nbsp;&nbsp;&nbsp;&nbsp;|--page1.md
 &nbsp;&nbsp;&nbsp;&nbsp;|--page2.md
&nbsp;&nbsp;|--subdir2
 &nbsp;&nbsp;&nbsp;&nbsp;|--page3.md
 &nbsp;&nbsp;&nbsp;&nbsp;|--page4.md

用这样的文件结构，使用 hexo g 是可以生成页面的，并且在 public 页面下有对应的目录层次。

也感谢你们的分享，我们才能用到好看的免费的页面 ^ ^

**Comment by ikeq** [comment]
#127
