### ISSUE TITLE
最大宽度按照比例放大就好了

### ISSUE THREAD

**Issue by toperc** [ikeq/hexo-theme-inside#131]
博客在笔记本上看着正好，但是到大屏幕高分屏上内容区的宽度很小，因为最大宽度是固定的，这就导致两边有很大的空白，不协调了。

**Comment by ikeq** [comment]
其实这个空白是风格，不过你这个意见也很好，可以让 content_width 支持自定义单位。

**Comment by toperc** [comment]
可以的

**Comment by ikeq** [comment]
#166
