### ISSUE TITLE
自定义plugins:

### ISSUE THREAD

**Issue by awnawnawn** [ikeq/hexo-theme-inside#134]
我在添加`script`时遇到了一些问题，这是我的调试代码
![捕获](https://user-images.githubusercontent.com/47672657/65009530-9eafd000-d93f-11e9-86bf-f70f6831d025.PNG)
 `alert('false')`

似乎 代码段 比 页面渲染 先执行了

我用了`setInterval`试了一下
![捕获as](https://user-images.githubusercontent.com/47672657/65009755-69f04880-d940-11e9-9eed-662f6a17701d.PNG)
`alert('true')`

我该如何实现页面渲染完之后再执行我的`script`呢?

**Comment by ikeq** [comment]
你选择 nav.eb 是要做什么？不建议这样用，因为 eb 可能会变～

**Comment by awnawnawn** [comment]
我想在里边添加一些自定义的标签内容，我知道会变～

**Comment by ikeq** [comment]
因为 SPA 的缘故（JS 渲染整个页面），局限很大，即使能够实现页面渲染之后执行脚本，视觉上也会有延迟，Angular 的 SSR（预渲染 HTML）又 shi 的不愿意多提，虽然我那个 blog 实现了，但很难集成到主题里，anyway，目前并不建议这么做。

计划换个框架（[Svelte](https://svelte.dev/) 看起来就很不错）重构一下前端，能更好的支持 SSR。

**Comment by awnawnawn** [comment]
@ikeq 好的，没事。我是有办法实现预期的效果，主题是很好的，一直支持~
