### ISSUE TITLE
请问移动端的侧边栏TOC可以支持跳转吗

### ISSUE THREAD

**Issue by YuxinZhaozyx** [ikeq/hexo-theme-inside#138]
我在PC端chrome浏览器可以用TOC跳转到指定标题位置，但是在Android端chrome浏览器上却只能查看TOC而无法跳转到选定的标题处。

**Comment by ikeq** [comment]
我的网站就可以跳啊

**Comment by YuxinZhaozyx** [comment]
我在chrome for android上开示例网站，部分可以跳转，部分不可以。
https://blog.oniuo.com/post/math-jax-ssr-example 可以跳转，但 https://blog.oniuo.com/post/integrating-algolia-search-in-theme-inside 跳转不了

**Comment by ikeq** [comment]
😑 我怎么可以

**Comment by YuxinZhaozyx** [comment]
能提供一下Chrome for Android的版本吗？
我的版本是Chrome 76.0.3809.132

**Comment by ikeq** [comment]
跟版本没关系，你是点了没反应吗

**Comment by YuxinZhaozyx** [comment]
是的，能显示TOC，但是点击没有反应

![Screenshot_20190924-185644](https://user-images.githubusercontent.com/32972764/65506111-67bc5a00-defd-11e9-8429-34ee754f714d.jpg)

**Comment by ikeq** [comment]
再现不了这个问题呃，不过我是 Chrome 77。

**Comment by YuxinZhaozyx** [comment]
目前在我的移动端上还是有个别post不能跳转，但是影响不大，先关了。谢谢
