### ISSUE TITLE
任意一级标题包含中文时右下角圆钮打不开TOC

### ISSUE THREAD

**Issue by YuxinZhaozyx** [ikeq/hexo-theme-inside#142]
post中任意一级标题包含中文时，右下角圆钮都打不开TOC，另外尝试了在移动端上打开，也是同样的问题，无法用圆钮打开，从屏幕右侧倒是可以直接拖出TOC，但是拖出来之后就收不回去了

**Comment by ikeq** [comment]
我的网站有这个问题吗

**Comment by YuxinZhaozyx** [comment]
你的网站没有这个问题。

**Comment by ikeq** [comment]
你的标题在 markdown 里是怎么写的，贴一条看看

**Comment by ikeq** [comment]
另外，是可以拖回去的啊，在 toc 边缘拖。

**Comment by YuxinZhaozyx** [comment]
这是[我网站里的一篇post](https://yuxinzhaozyx.github.io/what-is-RoI)，下面是它的markdown。我的网站里其他所有标题带中文的post也都打不开toc。

```
## RoI概念

![](./what-is-RoI/featured.png)

RoI的全称是Region of Interest，中文名称是"感兴趣区域"。

RoI是从图像中选择的一个图像区域，这个区域是你进行图像分析的重点。圈出这块区域可以得到一个子图像(subimage)，之后就可以在这个区域内使用进行进一步处理。

**目的：**

- 减少处理时间
- 增加精度
```

**Comment by YuxinZhaozyx** [comment]
移动端试过拖toc边缘，但只能拖回去一半，之后就卡住了，toc收不回去

**Comment by ikeq** [comment]
https://yuxinzhaozyx.github.io/api/d2hhdC1pcy1Sb0k.json?v=7ebb13
你的汉字全部转成 html 实体了，导致 getElementById('RoI&#x6982;&#x5FF5;') 失效，因为是无效 id，看看是哪里转的。

**Comment by YuxinZhaozyx** [comment]
非常感谢你花时间检查我的网站出的错误。

我进行了以下操作后恢复正常了：

`hexo init` 新建了一个博客，直接克隆 ikeq/hexo-theme-inside 到 themes 目录下，然后手动修改主题的 _config.yml 到跟原本有问题的博客一样；把 post 都复制到新的博客目录下，然后手动修改新博客的 _config.yml 跟原本一样，然后就好了，没搞明白为啥。
另外，我加入一段样式表的代码到主题 _config.yml 的 plugin 下，之前的问题出现了，但是我剪切掉重新粘贴又好了，没搞懂问题出在哪，但是目前恢复正常了。

**Comment by ikeq** [comment]
如果方便，提供下 plugin 代码，你可以删减到最小，只要能保证可以再现问题。

**Comment by YuxinZhaozyx** [comment]
操作系统：windows10 （已在两台windows10系统的电脑上复现）

问题复现：
1. 将 [blog-hexo-old-min.zip](https://github.com/YuxinZhaozyx/blog-hexo/releases/download/error-toc/blog-hexo-old-min.zip) 解压到文件夹 blog-hexo
2. `cd blog-hexo`
3. `npm install`
4. `hexo server`
5. http://localhost:4000 进入博客主页后打开唯一的一篇文章 “What is RoI”，无法打开TOC

注：主题部分只修改了_config.yml文件，其他文件没有修改
