### ISSUE TITLE
搜索出的文章，点击后会跳转主页

### ISSUE THREAD

**Issue by blackawn** [ikeq/hexo-theme-inside#143]
[链接地址](https://blackawn.me)
默认的holle wrold文章搜索可以跳转，其他添加的点击后重新跳转了主页
![GIF](https://user-images.githubusercontent.com/49859450/65881072-6be8eb80-e3c5-11e9-8145-53b62a6b740e.gif)

**Comment by ikeq** [comment]
大小写问题，请求 html 的时候服务器将 `testSearch` 转成 `testsearch`，直接点 列表可以打开是因为无 html 请求，走的前端路由，刷新后就不行了。

解决：
1. 看服务器哪里能配置大小写敏感；
2. .md 文件名使用连字符（不影响 title 使用驼峰式），比如 `test-search`。

推荐第二种。
