### ISSUE TITLE
设置disqus无效

### ISSUE THREAD

**Issue by JonTree** [ikeq/hexo-theme-inside#144]
//jonsblog-2.disqus.com/embed.js用浏览器可以进，但是直接设置上去之后 hexo g   hexo s 后没有任何效果，推送上去也没有

**Comment by Treeeeeeee** [comment]
我试了试livere的，可以，但是如果设置手动加载的话，加载不出来，应该不是网络原因，科学上网我也有

**Comment by ikeq** [comment]
comments 配置贴一下
