### ISSUE TITLE
目录bug

### ISSUE THREAD

**Issue by JonTree** [ikeq/hexo-theme-inside#145]
这个主题我超级喜欢，发现了一点bug，目录如果你依次点击1.1，1.2，1.3，点击完1.3之后再点击1.2是没有反应的，但是点击1.1是可以跳转到相应目录的

**Comment by ikeq** [comment]
看下是不是内容太短，已经在屏幕内了，所以没反应。

**Comment by Treeeeeeee** [comment]
应该不是，我点击1.2的目录时1.1的内容已经被顶出屏幕外了，但是依旧不可点击，我看手机上是没有问题的，只有pc版有问题。而且我查看你的blog是没有这个问题的。
简而言之：按次序依次点击相邻目录，然后点击距离最近点过的那一个是不可点击状态

**Comment by ikeq** [comment]
哪里有例子，给个链接我看看。

**Comment by Treeeeeeee** [comment]
https://treeeeeeee.github.io/2019/10/01/%E5%9F%BA%E4%BA%8E%E9%85%B7q%E5%B9%B3%E5%8F%B0%E7%9A%84%E7%AE%A1%E7%90%86%E6%9C%BA%E5%99%A8%E4%BA%BA

**Comment by Treeeeeeee** [comment]
你看看

**Comment by ikeq** [comment]
没毛病，( ﹁ ﹁ )
