### ISSUE TITLE
go语言代码块显示错误

### ISSUE THREAD

**Issue by YuxinZhaozyx** [ikeq/hexo-theme-inside#146]
markdown 如下：

`````
# 变量

```go
var variablename type
var vname1, vname2, vname3 type 
var vname1, vname2, vname3 type = value1, value2, value3
var vname1, vname2, vname3 = value1, value2, value3
vname1, vname2, vname3 := value1, value2, value3 // 只能用在函数内部，局部变量
var(
   vname1 type
   vname2 type
) // 只能用在函数外，全局变量
```

# 常量

```go
const constantName type = value
const constantName = value
const(
	name1 = value1
    name2 = value2
)
```
`````

`hexo server` 在本地启动后go语言的代码块显示错误：

![image](https://user-images.githubusercontent.com/32972764/66032735-8394b100-e538-11e9-8635-a0188325902f.png)

 **注：**

将 go 换成 golang 后显示正常:

`````
# 变量

```golang
var variablename type
var vname1, vname2, vname3 type 
var vname1, vname2, vname3 type = value1, value2, value3
var vname1, vname2, vname3 = value1, value2, value3
vname1, vname2, vname3 := value1, value2, value3 // 只能用在函数内部，局部变量
var(
   vname1 type
   vname2 type
) // 只能用在函数外，全局变量
```

# 常量

```golang
const constantName type = value
const constantName = value
const(
	name1 = value1
    name2 = value2
)
```
`````

**Comment by ikeq** [comment]
我这边看是好的，如果方便发个外网链接看看。

**Comment by YuxinZhaozyx** [comment]
https://yuxinzhaozyx.github.io/hexo-theme-inside-error-example

**Comment by ikeq** [comment]
语法高亮插件添加的 `.go` 样式类名和主题冲突了（我本地调试由于是 dev 启动，所以没冲突），其实这个语言类名除了冲突没别的作用，我下次更新删了它，多谢反馈。

**Comment by ikeq** [comment]
友情提示，主题一大亮点是 `accent_color` 这个设置：
```yml
appearance:
  # Accent color, 试试紫色 #673AB7 ?
  accent_color: '#673AB7'
```

**Comment by YuxinZhaozyx** [comment]
> 友情提示，主题一大亮点是 `accent_color` 这个设置：
> 
> ```yaml
> appearance:
>   # Accent color, 试试紫色 #673AB7 ?
>   accent_color: '#673AB7'
> ```

非常感谢，主题很棒。我换了好几个主题才遇到这个简洁美观而且功能强大的主题，之前用过几个hugo和hexo的其他主题，但是因为我是用Typora来写markdown的，如果markdown渲染引擎不换katex，写的数学公式就不能正常显示，还得手动转义；换了katex，主题就会有很多地方的样式出现问题。这个主题很美观，而且能和Typora完美对接，用起来很轻松:smile:
