### ISSUE TITLE
Empty sidebar title link

### ISSUE THREAD

**Issue by kidonng** [ikeq/hexo-theme-inside#151]
https://bitbucket.org/ikeq/hexo-theme-inside-ng/src/0c775104c8eb921c4c41ccc04000f9ccaf372f9a/src/app/components/sidebar/sidebar.component.html#lines-9

```html
<a class="author-name theme-font-logo theme-color-full" href>{{config.author}}</a>
```

`href` attibute is empty. This looks like a mistake of:

```html
<a class="author-name theme-font-logo theme-color-full" href="/">{{config.author}}</a>
```

Or it should be `routerLink` (I'm not familiar with Angular, sorry).

**Comment by ikeq** [comment]
`href` is equivalent to `href=""`, which will perform a hard reload (Not very SEO friendly though).

**Comment by kidonng** [comment]
Yes, but why it is necessary?

**Comment by ikeq** [comment]
It's not necessary, but a regular “back to home” would be a little bit boring since we already have a Home link, so it's kinda like a suprise 😄.

But feel free to comment if you have better suggestion!

**Comment by kidonng** [comment]
I would suggest using ordinary `routerLink` as it won't undermine the user experience. It's just a personal taste, you can leave it as you like 😉
