### ISSUE TITLE
关于添加Valine评论系统之后，Sidebar profile：个人名称显示错位！

### ISSUE THREAD

**Issue by BluerAngala** [ikeq/hexo-theme-inside#153]
- 你好，我想请问
- 这个添加了关于添加Valine评论系统之后，Sidebar profile：个人名称显示错位！该怎么处理？
- 已经尝试去css文件去修改，但是对于 主题 下面的 /  source 存在很多疑问，不知道该怎么改，麻烦大神在闲暇之余能给予回复，非常感谢！

![360截图17001014336914](https://user-images.githubusercontent.com/49632180/66800253-1c6af980-ef47-11e9-88c2-0d68bc546929.png)

**Comment by ikeq** [comment]
我提了个 bug 给 valine 这个项目，https://github.com/xCss/Valine/issues/216

**Comment by ikeq** [comment]
我提了个 issue 给 valine 这个项目，https://github.com/xCss/Valine/issues/216

**Comment by BluerAngala** [comment]
> 我提了个 issue 给 valine 这个项目，[xCss/Valine#216](https://github.com/xCss/Valine/issues/216)

**Comment by BluerAngala** [comment]
这个主题实在是太好了，我真的爱不释手，很想做成博客记录一些事情，但是有些小地方我想进行修改，但是我不是很明白 hexo-theme-inside 的文件性质。

额，怎么说呢，想进行一些细致的修改，不知道在哪个文件改动，例如：我想给侧边栏的文字配上图标（home/ about 等）；改变右下角的功能球的颜色，添加可以拖动的代码等。

麻烦告知大致思路，不胜感激~

**Comment by YES-Lee** [comment]
@BluerAngala 

这个主题是使用angular开发的spa应用，需要修改源代码，源码仓库地址：[https://bitbucket.org/ikeq/hexo-theme-inside-ng/src/master/](https://bitbucket.org/ikeq/hexo-theme-inside-ng/src/master/)

我也非常喜欢这个主题，就是因为这个主题才入坑的hexo，我也在研究源码，有兴趣可以一起交流。

**Comment by ikeq** [comment]
@YES-Lee 源码有些地方挺乱的😂，因为主题才入的 hexo 的坑，太褒奖了。

**Comment by ikeq** [comment]
@BluerAngala 右下角的 fab 按钮的填充色是根据 `appearance.accent_color` 这个设置变的，也是网站的整体色调。

**Comment by YES-Lee** [comment]
@ikeq 
哈哈，确实很喜欢你的主题。也是因为之前没见过spa的主题，发现这个想法挺好。希望能在源码上贡献几行代码😄

**Comment by BluerAngala** [comment]
非常感谢，这主题真的让我爱不释手，很想尽快完善成直接的博客，感谢 @ikeq @YES-Lee

**Comment by ikeq** [comment]
类名冲突的问题，valine 的作者似乎很忙，你可以：

1. 自己改 valine.css，把 `.v` 改成 `.valine`；
2. 或者封装成自定义组件，shadow dom 有样式隔离。

前者比较简单，bug 先关了，另外也考虑写一个基于 leancloud 的评论系统以更好的支持 SPA，就是最近忙的一b。
