### ISSUE TITLE
在文章中注入脚本

### ISSUE THREAD

**Issue by YES-Lee** [ikeq/hexo-theme-inside#154]
## 需求

今天有个需求，我需要在特定文章中插入一些js代码，让文章增加一些交互功能，如图所示（查看此地址：[https://johnsonlee.site/post/web-components](https://johnsonlee.site/post/web-components)）
![image](https://user-images.githubusercontent.com/19748456/66815504-f0fa0600-ef6a-11e9-8fa3-17ea9fcabd02.png)

## 我的解决方案

我直接在front-matter中添加了脚本地址，`layout`模板里面将脚本插入页面

文章Front-matter

```yml
scripts:
- my-progress.js
```

layout/index.ejs

```html
<body>
...
<%- (page.scripts || []).map(u => js(url_for(page.path) + u)) %>
...
</body>
```

## 问题

由于是SPA，在文章页面需要刷新才会加载我插入的脚本，是否有什么方式可以解决这个问题？

**Comment by ikeq** [comment]
针对部分页面的脚本目前没有好办法，不过你可以直接在 md 里写 <script>，是可以执行的，我自己目前是写了个自定义 tag 来将 <script> 插入 md。

比如代码高亮的页面：
```md
{% snippet theme/snippets/highlighting-palette.html %}
```

另外也可以考虑使用 web component，毕竟 9012 年了，而且 web component 可以写 unmount 时的一些清除代码，更安全。

比如我侧边栏那个换肤的，最近在改：
```yml
plugins:
  - /wc.5739bf5d.js # IIFE 注册自定义组件
  - position: sidebar
    template: <is-palette></is-palette>

**Comment by ikeq** [comment]
snippet tag 的代码供你参考：
```js
// themes/scripts/snippet.js
const fs = require('fs');
const path = require('path');
const cheerio = require('cheerio');
const utils = require('../lib/utils');


hexo.extend.tag.register('snippet', function ([pathname]) {
  const code = loadSnippet(pathname)
  if (!code) return ''

  const $ = cheerio.load(code, { decodeEntities: false });
  $.root().children('script').each(function () {
    const $script = $(this),
      html = $script.html();

    if (html) $script.replaceWith(utils.snippet(html));
  });

  return utils.minifyHtml($.html())
})

function loadSnippet(pathname) {
  if (!pathname) return ''

  const templateUrl = path.join(hexo.base_dir, pathname);
  if (!fs.existsSync(templateUrl)) return '';

  return fs.readFileSync(templateUrl, 'utf8');
}
```

用法就是：
{% snippet snippets/snippet-1.html %}

路径解析相对于 hexo 根目录。

**Comment by YES-Lee** [comment]
@ikeq 
感谢。

确实，我这个需求大多时候都是写web component，只不过不想在全局注册，想着用到的文章单独注册。我就先试试直接注入script到md吧
