### ISSUE TITLE
关于hexo-theme-inside 的api命名，存在问题！

### ISSUE THREAD

**Issue by BluerAngala** [ikeq/hexo-theme-inside#159]
我没有修改关于js的任何配置，在加入79篇文章之后，这个api生成的文件名太长，我尝试去找到这个路径文件，找到了文件，但是这个是主题自动生成的，应该是命名时文件名太长了。

麻烦大神闲暇之余帮忙看看，我该怎么解决？

![360截图16790526113110144](https://user-images.githubusercontent.com/49632180/67154124-d936cf00-f328-11e9-993a-6877addc2ac4.png)
![360截图17100813777684](https://user-images.githubusercontent.com/49632180/67154156-91fd0e00-f329-11e9-8c48-79d76dbc8168.png)

**Comment by ikeq** [comment]
你的.md文件名叫啥

**Comment by BluerAngala** [comment]
类似这种：法考倒计时5：黎明前的黑暗，谈不上斗志昂扬，重复中迈向终点.md
是不是文件名为中文出现的问题？

**Comment by ikeq** [comment]
你截图的文件名，比 `法考倒计时5：黎明前的黑暗，谈不上斗志昂扬，重复中迈向终点` 长的多吧，windows 下 文件名长度限制为 255，汉字字符转 base64 为 4 个字符，英文为 2 个字符，你自己悠着点~

**Comment by BluerAngala** [comment]
好，之前没想到这个点，以后我把题目都换成英文，学到了!
