### ISSUE TITLE
关于hexo-theme-inside 添加lazyload失败！

### ISSUE THREAD

**Issue by BluerAngala** [ikeq/hexo-theme-inside#160]
想要给hexo-theme-inside 添加图片懒加载，选中的方案是添加js插件 lazyload，源码链接为：https://github.com/tuupola/lazyload 

经过尝试修改，遇到一些问题：
1. 需要改动<img> class name
2. 需要添加 在 <img> 中添加 [data-src]
3. 需要添加固定的宽度和高度
4. 我无法找到hexo-theme-inside修改以上属性的代码位置，多次尝试按照现有的<img> class name 进行若干配置，最终失败，无奈只能求助，希望能给予解答，谢谢！

![360截图162708296697121](https://user-images.githubusercontent.com/49632180/67254473-c4387800-f4af-11e9-8b82-4d830dabeb06.png)

**Comment by YES-Lee** [comment]
该主题是使用angular开发的单页面应用，页面的渲染代码全部经过了压缩，没法直接修改，只能修改源码重新编译。

不过文章中的图片要实现懒加载还是有别的方法的，比如使用自定义tag：

```javascript
hexo.extend.tag.register('lazy_image', ([filename]) => {
  return `<img class="lazyoad" data-src="${path.join(hexo.source_dir, '_posts', filename)}">`
})
```

然后在md中使用
{% lazy_image IMAGE_NAME.jpg %}

**Comment by BluerAngala** [comment]
你的意思是在源码中自定义tag，然后在md文件中，对于文章中的图片链接格式按照{% lazy_image IMAGE_NAME.jpg %} 进行修改，是吗？

那么是在该在theme文件夹中的哪个文件进行修改？

另外，md文件中的图片如果是已经上传图床的网络链接，如![](https://img.vim-cn.com/9e/cb0bf58d6284bac6058efac4780098fc23559f.jpg)，按照你所说的方法，似乎无法实现，我该如何解决？

**Comment by BluerAngala** [comment]
经过多次测试和修改，发现以下问题：

### 1. 文章封面图报错：

正常显示：`thumbnail: https://img.vim-cn.com/0d/3901e6b34610e9d2206c93250d979bba214b36.jpg`；

修改成：`{% lazy_image http://miaoshu-1253346366.file.myqcloud.com/user/74069/images/1564546374272.png %}`，报错

修改成：`thumbnail:  {% lazy_image http://miaoshu-1253346366.file.myqcloud.com/user/74069/images/1564546374272.png %}`，报错

如图：

![360截图17571117548494](https://user-images.githubusercontent.com/49632180/67266251-58233780-f4e2-11e9-8cb1-c49936b5a8d5.png)
![360截图1657020589117123](https://user-images.githubusercontent.com/49632180/67266557-12b33a00-f4e3-11e9-8def-ada8e52b4453.png)




### 2. 文章内图片无法显示

文章内的图片虽然修改了为  `{% lazy_image https://img.vim-cn.com/9e/cb0bf58d6284bac6058efac4780098fc23559f.jpg %}` 格式

但是无法显示，原因是html生成的时候没有生成`<img class="lazyload" data-src="${url}">`

**Comment by YES-Lee** [comment]
建议查看官方文档

**Comment by ikeq** [comment]
frontmatter 里写 tag，没有这样的用法吧。

lazyload 不好搞，不过值得一提的是，不少浏览器已经原生支持 lazyload 了，见 https://github.com/scott-little/lazyload ，下次更新我会顺便带上这个 `loading="lazy"` 属性，不过只是延后加载，省流量，不会有转圈圈。
