### ISSUE TITLE
CDN加速问题

### ISSUE THREAD

**Issue by YES-Lee** [ikeq/hexo-theme-inside#168]
如题，我使用了CDN加速，但是配置data_prefix和static_prefix之后，开发模式无法正常加载，因为此时静态文件没有发布。

**Comment by YES-Lee** [comment]
搞定了，加了个环境变量控制

**Comment by ikeq** [comment]
改了主题源码么

**Comment by YES-Lee** [comment]
@ikeq 
是的，我fork了一个，加了些自己的东西

**Comment by ikeq** [comment]
@YES-Lee 建了个交流群 (QQ)，有兴趣可以加～

977807226
