### ISSUE TITLE
gitment使用出现[object ProgressEvent]

### ISSUE THREAD

**Issue by LewisKulen** [ikeq/hexo-theme-inside#173]
gitment博主换了服务器，但好像我修改了之后还是行不通，请问是我哪里写错了吗？
plugins:
  - https://www.wenjunjiang.win/css/gitment.css
  - https://www.wenjunjiang.win/js/gitment.js
  - position: comments
    template: |
      <div id="gitment"></div>
      <script>
        if (!window.__gitment) window.__gitment = new Gitment({
          owner: 'LewisKulen',
          repo: 'https://github.com/LewisKulen/blog-comment',
          oauth: {
            client_id: '******',
            client_secret: '******',
          },
        });
        Object.assign(__gitment, {
          id: decodeURIComponent(location.pathname),
          title: document.title,
          link: location.href,
        });
        __gitment.update();
        __gitment.render('gitment');
      </script>

**Comment by ikeq** [comment]
请说详细一点
