### ISSUE TITLE
content_width比例缩放有问题

### ISSUE THREAD

**Issue by toperc** [ikeq/hexo-theme-inside#176]
content_width如果按照百分比或者rem，当在小屏上会出现右边空出一片，可以将浏览器宽度缩到最小查看。

**Comment by ikeq** [comment]
小屏指多小的屏幕

**Comment by toperc** [comment]
> 
> 
> 小屏指多小的屏幕

我在4.7的iphone8上即可出现，其实就是移动端适配那个尺寸就会出现了

**Comment by ikeq** [comment]
已修复， #178 。

另外建了个交流群 (QQ)，有兴趣可以加～

977807226

**Comment by toperc** [comment]
> 
> 
> 已修复， #178 。
> 
> 另外建了个交流群 (QQ)，有兴趣可以加～
> 
> 977807226

OK， great!
