### ISSUE TITLE
左侧滑出

### ISSUE THREAD

**Issue by blackawn** [ikeq/hexo-theme-inside#181]
请教一下主题的在移动端上，从左侧滑出是怎么实现？恳请有demo

**Comment by ikeq** [comment]
源码都给你了🤔

**Comment by blackawn** [comment]
@ikeq 打包过了呀，这是人看得了的？:hushed:

**Comment by ikeq** [comment]
我指前端源码，README 翻到最下边。

**Comment by ikeq** [comment]
我指前端源码，README 翻到最下边。

**Comment by blackawn** [comment]
@ikeq 我看了utils.ts，我目前还没接触到ts，js也没有掌握多少:frowning:，尝试失败:hear_no_evil:

**Comment by ikeq** [comment]
建了个交流群 (QQ)，有兴趣可以加～

977807226
