### ISSUE TITLE
如何添加newsletter subscribe功能

### ISSUE THREAD

**Issue by lzh626** [ikeq/hexo-theme-inside#189]
希望在左边导航部分home菜单的上方添加一个card,里面有一个邮件输入框和一个subscribe的submit按钮，post的api已有，请问需要在哪里修改?
谢谢

**Comment by ikeq** [comment]
目前只能添加到导航的下边哦，更灵活的配置，或者甚至主题集成 subscribe 功能还需要再思考以下，多谢支持～
