### ISSUE TITLE
下划线样式在浏览器点击返回按钮时出现问题

### ISSUE THREAD

**Issue by fiteen** [ikeq/hexo-theme-inside#190]
### 环境：
- 主题版本：hexo 4.2 + inside 2.6.0
- 系统+浏览器：Mac OS X 10.15.1 + Chrome v79.0.3945.130

#### 场景1 - Sidebar

**步骤**：

1. 在谷歌浏览器中打开[我的博客 - Archives 页](https://blog.fiteen.top)，此时分类指向 `Archives`；
2. 再点击 `Tags` 分类；
3. 接着点击浏览器左上角的返回按钮；
4. 出现 `Archives ` 和 `Tags` 都有下划线的情况。

**截图**：

![inside-underline-bug-1](https://gitee.com/fiteen/image-host/raw/master/uPic/inside-underline-bug-1.png)

#### 场景2 - Categories

**步骤**：

1. 在谷歌浏览器中打开[我的博客 - Categories 页](https://blog.fiteen.top/categories/Android)，此时分类指向 `Android`；
2. 再点击 `Git` 分类；
3. 接着点击浏览器左上角的返回按钮；
4. 出现 `Android` 和 `Git` 都有下划线的情况。

**截图**：

![inside-underline-bug-2](https://gitee.com/fiteen/image-host/raw/master/uPic/inside-underline-bug-2.png)

**Comment by ikeq** [comment]
触屏上才会出现对吧

**Comment by ikeq** [comment]
#191
