### ISSUE TITLE
会添加 SSR 功能吗？

### ISSUE THREAD

**Issue by MoeCasts** [ikeq/hexo-theme-inside#196]
没有服务端渲染的话，国内搜索引擎的收录并不好。

**Comment by ikeq** [comment]
@MoeCasts 会的，但 angular 目前提供的 ssr 非常不好集成，考虑找时间换个框架，所以没那么快，我倒是可以先写篇 blog，介绍下怎么先自己 DIY，使用 angular 的 ssr 功能。

**Comment by MoeCasts** [comment]
@ikeq 十分感谢 :)

**Comment by ikeq** [comment]
#231
