### ISSUE TITLE
可能由于高度计算出错的问题导致layout出错

### ISSUE THREAD

**Issue by michaelfyc** [ikeq/hexo-theme-inside#198]
主题版本：2.6.2
问题描述：
在sidebar插入了aplayer，出现
![wrong-layout](https://user-images.githubusercontent.com/45136049/75603593-dc2da180-5b0a-11ea-9363-0390b5760290.png)
检查样式发现footer加了φed类。
从底部打开开发者工具后，layout恢复正常，φed被removed。
![right-layout](https://user-images.githubusercontent.com/45136049/75603697-f025d300-5b0b-11ea-80b5-00fef68daff9.png)
前端比较菜，据我猜测是![relative-code](https://user-images.githubusercontent.com/45136049/75603668-873e5b00-5b0b-11ea-8171-12c4c563aa38.png)处高度计算出错..

**Comment by ikeq** [comment]
没有办法做到自适应插入的 plugin 的高度，因为是异步的，两个解决办法：
1. plugin 写死高度再插入；
2. 等 plugin 初始化完毕，高度稳定后手动触发下 window 的 resize 事件。
