### ISSUE TITLE
代码行号错乱

### ISSUE THREAD

**Issue by wolibo** [ikeq/hexo-theme-inside#202]
主题很赞，遇到一些问题反馈一下
![](https://file.pyai.top/img/20200306134716.png)
当代码块超过100行以后，在safari浏览器里面就会出现这种错乱的问题，其他浏览器正常。
文章地址：https://blog.pyai.top/2020/prev-4

**Comment by ikeq** [comment]
兼容问题，已修复 [2.6.3](https://github.com/ikeq/hexo-theme-inside/releases/tag/2.6.3)
