### ISSUE TITLE
可以添加一个文章隐藏的功能吗？

### ISSUE THREAD

**Issue by OuYanghaoyue** [ikeq/hexo-theme-inside#213]
可以添加一个文章隐藏的功能吗？不在achive中显示出来，但是可以通过链接直接访问
在front-matter中添加一个关键字hidden以此来控制文章是否显示，谢谢up

**Comment by zhangshen147** [comment]
同需要此功能

**Comment by ikeq** [comment]
hexo默认主题是否支持此功能？

**Comment by zhangshen147** [comment]
> hexo默认主题是否支持此功能？

应该不支持吧，没听说过。

**Comment by zhangshen147** [comment]
> hexo默认主题是否支持此功能？

作者，加密或隐藏文章（最好是加密）的功能有计划吗，强烈请求啊，已经有一个叫hexo-blog-encrypt的插件可以实现，但在我们的inside主题中不兼容，望能解决一下bug集成进来，在下是做后端的，能力有限，如有必要，愿意付费。

**Comment by ikeq** [comment]
目前正在内置一些常用的插件，可以做到开箱即用，包含了加密，即将完成。😋

**Comment by zhangshen147** [comment]
> 目前正在内置一些常用的插件，可以做到开箱即用，包含了加密，即将完成。😋

爱您😘

**Comment by ikeq** [comment]
https://blog.oniuo.com/theme-inside/docs/built-in-plugins

**Comment by ikeq** [comment]
于 front matter 增加了一个 `visible` 字段，设置为 `false` 即隐藏，详见 [theme-inside/docs/front-matter](https://blog.oniuo.com/theme-inside/docs/front-matter#%E5%90%8C%E6%97%B6%E9%80%82%E7%94%A8%E4%BA%8E-page-%E5%92%8C-post)。
