### ISSUE TITLE
请问主题_config.yml中data_dir是干啥用的？

### ISSUE THREAD

**Issue by shuntan** [ikeq/hexo-theme-inside#215]
`# Folder where json file will be generated to, default to 'api'`
`data_dir: api`
Q1:除了api还能设置成什么？

Q2: 我有个小场景，post区域装了一个hexo-blog-encrypt的插件，需要每次页面刷新的时候重新加载js。
但是我看点击下一篇文章的时候，没有真正刷新页面。而是加载了一个json文件，https://xxxxx/api/cG9zdC9pbnNpZGUtdGhlbWUtc2hvd2Nhc2U.json?v=c0e01e，
好像是做了缓存优化，导致js没成功加载。能否把这个功能关掉？

**Comment by ikeq** [comment]
1. 还可设置成 `asdf`
2. 没法直接支持 hexo-blog-encrypt，懂一点前端可以自己改
