### ISSUE TITLE
侧边栏menu圆点的填充

### ISSUE THREAD

**Issue by MAGI003769** [ikeq/hexo-theme-inside#218]
问题是个小细节。侧边栏渲染出来menu的圆点demon里面是浅色填充，但是我本地渲染就是深色填充。想问一下是哪里出了问题。
![image](https://user-images.githubusercontent.com/23695704/81517467-e381e000-92ef-11ea-85cd-b7d769e5329f.png)
![image](https://user-images.githubusercontent.com/23695704/81517492-f98fa080-92ef-11ea-8e68-d000ac7830e4.png)

**Comment by ikeq** [comment]
其实这个黑点是你的背景图片，你可以再多设置一下背景色就好了，比如：
```yml
appearance:
  background: #8db2b8 https://post-pic.nos-eastchina1.126.net/blur-wallpapers.jpg
```

**Comment by ikeq** [comment]
另外你的主题似乎不是最新版。
