### ISSUE TITLE
How to deploy this theme with .travis.yml

### ISSUE THREAD

**Issue by system-thoughts** [ikeq/hexo-theme-inside#251]
Hello,  I have a question about auto deploying inside theme withe .travis.yml. 
I do the following steps to install this theme:
1. Download the latest version from releases, unpack and rename to inside, then put it in the themes directory.
2. Config HEXO/_config.yml as follows:
`theme: inside`
then I push this change to github, Travis CI build failed:
https://travis-ci.com/github/system-thoughts/system-thoughts.github.io/builds/203556108

My github page repo is :
https://github.com/system-thoughts/system-thoughts.github.io
the src code is on src branch

**Comment by ikeq** [comment]
[markdown-it](https://github.com/markdown-it/markdown-it) and [markdown-it-container](https://github.com/markdown-it/markdown-it-container) are required, add them as dependencies in`site/package.json`, sorry for the incomplete documentation.

**Comment by system-thoughts** [comment]
ikeq, thanks for your reply, I am a newbie in using Nodejs and angular. The theme may be better for manually deployment or Travis CI deployment out of box. Thanks again, I will try your advice later and reply ASAP.

**Comment by system-thoughts** [comment]
After I add markdown-it and markdown-it-container  into `site/package.json`, still failure, this is build log: https://travis-ci.com/github/system-thoughts/system-thoughts.github.io/builds/204843733

And the github page src code is hosted in master branch:
https://github.com/system-thoughts/system-thoughts.github.io/tree/master

**Comment by ikeq** [comment]
Set Node version to 12 at [.travis.yml](https://github.com/system-thoughts/system-thoughts.github.io/blob/91ebd83fac4bb8e84596e6e6a08768599e7d9507/.travis.yml#L3)

**Comment by system-thoughts** [comment]
Thanks again, it's solved!
