### ISSUE TITLE
发布npm包

### ISSUE THREAD

**Issue by AnotiaWang** [ikeq/hexo-theme-inside#259]
能把主题做成npm依赖包吗

**Comment by ikeq** [comment]
hexo 官方刚支持通过 npm 安装，我有时间了就跟进🌝

**Comment by AnotiaWang** [comment]
好的，大佬辛苦了

**Comment by ikeq** [comment]
支持了 [hexo-theme-inside](https://www.npmjs.com/package/hexo-theme-inside)，推荐的使用方式如下：

1\. Locate to `project/` and run

```bash
npm install hexo-theme-inside
```

2\. Config `project/_config.yml`

```yaml
theme: inside
```

3\. Copy [_config.yml](https://github.com/ikeq/hexo-theme-inside/blob/master/_config.yml) to `project/_config.inside.yml`, see [here](https://blog.oniuo.com/theme-inside) for full documentation.
