### ISSUE TITLE
关于字体

### ISSUE THREAD

**Issue by Jedore** [ikeq/hexo-theme-inside#262]
修改_config.yml文件中的字体，在url后随便增加一个字体，结果本地跑起来没问题，部署到gitee page后，请求google font总是出问题,如下
```
https://fonts.googleapis.com/css?family=Tangerine:bold,bolditalic|Consolas|Droid Sans
```
火狐 报
```
来自“https://fonts.googleapis.com/css?family=Tangerine:bold,bolditalic|Consolas|Droid+Sans”的资源已被阻止，因为 MIME 类型（“text/html”）不匹配（X-Content-Type-Options: nosniff）。
```
谷歌也报403

但是把上面的链接放入浏览器直接请求是正常的

**Comment by ikeq** [comment]
`https://fonts.googleapis.com/css?family=Tangerine:bold,bolditalic|Consolas|Droid+Sans` 这样试试？

**Comment by ikeq** [comment]
可能是 gitee 的锅，github pages 不香吗，还没有广告。

**Comment by 0x01x0** [comment]
> 可能是 gitee 的锅，github pages 不香吗，还没有广告。

GitHub有时候不能稳定访问 哈哈哈哈

**Comment by Jedore** [comment]
> `https://fonts.googleapis.com/css?family=Tangerine:bold,bolditalic|Consolas|Droid+Sans` 这样试试？

_config.yml 中就是这样写的，放弃了放弃了~~~~
