### ISSUE TITLE
缺少必要模块: Cannot find module 'markdown-it'

### ISSUE THREAD

**Issue by Qyir** [ikeq/hexo-theme-inside#266]
- 主题版本：2.7.0-beta.10 ( from release )

网站生成时显示 `err: Error: Cannot find module 'markdown-it'` 等信息

需要进入主题文件夹依据 `package.json` 手动安装缺少的模块，才能解决

**Comment by ikeq** [comment]
所以你不是已经解决了吗

**Comment by ikeq** [comment]
就两个依赖 markdown-it 和 markdown-it-container，项目根目录安装即可

**Comment by Qyir** [comment]
呃，解决是解决了……不过打包的时候还是把模块一起放进去吧😂，少些麻烦。

不过还是谢谢了，这个主题做的相当精致，👍

**Comment by ikeq** [comment]
现在不推荐下载 releases 进行安装了，看[这里](https://github.com/ikeq/hexo-theme-inside/blob/dev/README_zh-Hans.md#%E5%AE%89%E8%A3%85)。
