### ISSUE TITLE
refresh page throw 404

### ISSUE THREAD

**Issue by Asinta** [ikeq/hexo-theme-inside#268]
![image](https://user-images.githubusercontent.com/52993526/110000765-9ffcd480-7d4e-11eb-8f33-fd45aa70939c.png)
![image](https://user-images.githubusercontent.com/52993526/110001818-bb1c1400-7d4f-11eb-8759-d6763c8f81a7.png)

hexo: 5.4.0
inside: 2.7.0-beta.10
node: v14.15.1
npm: 6.14.8

When I refresh page in my post, this error throws. But I don't know why, same in local:
![image](https://user-images.githubusercontent.com/52993526/110001882-ccfdb700-7d4f-11eb-86ed-8ced34e75dd6.png)

Also, does not show view statistics on post page even I configured my GA UV-{number}, is there anything else need to config?
![image](https://user-images.githubusercontent.com/52993526/110002390-472e3b80-7d50-11eb-94e6-c0b2e6c6d643.png)

**Comment by Asinta** [comment]
看起来是生成出来的路径这里有点问题：
![image](https://user-images.githubusercontent.com/52993526/110127648-d7c45480-7e00-11eb-8404-52b4e2d4ab2a.png)
但是我找不到在哪里修改

**Comment by ikeq** [comment]
damn #273
