### ISSUE TITLE
文章访问统计功能

### ISSUE THREAD

**Issue by xuxusheng** [ikeq/hexo-theme-inside#269]
请问会考虑集成下文章访问量统计的功能吗

![image](https://user-images.githubusercontent.com/15248446/110457335-7e606c00-8105-11eb-8adc-fb76f1724f79.png)

**Comment by derbirch** [comment]
这个已经集成了，基于leancloud的，引用一个js就行，你可以去群主博客找源码api key改成自己的

**Comment by xuxusheng** [comment]
@derbirch 你好，我尝试找了一下作者的博客和文档，发现是实现了这个功能的，但是我没有找到相应的文档说明，能麻烦发一下链接我参考一下吗，谢谢了。

**Comment by ikeq** [comment]
目前主题支持 pv 展示，但不提供任何数据服务，我个人在用 leancloud。

主题 pv 展示通过下面代码实现：
```js
document.dispatchEvent(
  new CustomEvent('inside', {
    detail: {
      type: 'pv',
      data: {
        // [slug]: 第三方获取的 pv 数
        [location.pathname.substring(1)]: 999,
      },
    },
  })
);
```

### 说明
基于 hexo 的博客是静态的，所以统计数据的展示都是异步填充，很多主题是通过类似
`document.getElementById('#stat_pv').textContent = 999` 的方式。

由于 inside 主题是基于 angular 的 SPA，所以采用的是更合理的自定义事件的方式：

- 事件类型：`inside`
- 参数对象：
   ```ts
   { type: 'pv', data: { [slug: string]: string | number } }
   ```

**Comment by xuxusheng** [comment]
@ikeq 好的，谢谢了
