### ISSUE TITLE
Ability to use a page as root index? (non-blog homepage)

### ISSUE THREAD

**Issue by chelsea-codes** [ikeq/hexo-theme-inside#295]
Hi, thanks for this awesome theme!

I am wondering if there is a way to set the root index (homepage) to an .md file rather than the list of blog posts using this theme (without changing theme source code)? 

I have been able to follow the instructions [here](https://github.com/hexojs/hexo/issues/1077#issuecomment-536333536) to do this with other themes, such as 'clean', but I haven't been able to get the same outcome with this theme.

Any help is appreciated, thanks!

Chelsea

**Comment by chelsea-codes** [comment]
Also, reading through the source code I saw [this](https://github.com/ikeq/hexo-theme-inside/blob/70a24229dbe4c8f142fabc497cdd9fa8d80f013b/lib/generator/index.js#L12) in lib/generator/index.js.

Am I understanding correctly that this action allows the theme to override the default index generation behavior? Is that possibly why the solution [here ](https://github.com/hexojs/hexo/issues/1077#issuecomment-536333536) does not work?

Thanks

**Comment by ikeq** [comment]
Sorry for the late reply, I supported this feature at [2.7.0-beta.22](https://github.com/ikeq/hexo-theme-inside/releases/tag/2.7.0-beta.22) (#298). 
Now you can set `permalink: /` in the front matter of any post or page to set them as index, for instance:

```md
---
title: About
permalink: /
---

## About
```
