### ISSUE TITLE
how to add LineBreak to `bio`

### ISSUE THREAD

**Issue by nor0x** [ikeq/hexo-theme-inside#300]
is it possible to add a newline like `<br />` to the bio text render a break and text on a new line?

i have already tried the following syntax but didn't have any luck so far

``` 
  bio: |+
    Hello World!
     
    this should be in a new line
```

``` 
  bio:
     Hello World! \n this should be in a new line
```

``` 
  bio: |
    Hello World! \n
    this should be in a new line
```

**Comment by ikeq** [comment]
supported both syntax (`\n` and `<br>`) #302
