### ISSUE TITLE
头像不显示了

### ISSUE THREAD

**Issue by QingYiXiaoYao** [ikeq/hexo-theme-inside#336]
## 头像不显示了

主题里按照设置 在profile里设置了 avatar 后，不显示图片

<img width="280" alt="image" src="https://user-images.githubusercontent.com/58292274/217078828-bc223a89-3f0e-425f-8fe8-2b0d84c2efe6.png">

**Comment by ikeq** [comment]
默认通过配置的 email 自动生成 gravatar 的头像链接，境内有可能无法访问，可显式设置头像地址。如：

```yml
profile:
  avatar: https://lean.oniuo.com/Ny1EkTVcHfEihB4uWMMNayymSjaRXhUo/06818ca4361a28447cffdd2daaed2799.jpeg
```
