### ISSUE TITLE
Where to find front-end source code?

### ISSUE THREAD

**Issue by ikeq** [ikeq/hexo-theme-inside#43]
Right here. https://bitbucket.org/ikeq/hexo-theme-inside-ng

**Comment by bob80842** [comment]
The link doesn't seem to work anymore. Could it please be updated when you have a chance?

**Comment by ikeq** [comment]
@bob80842 Updated.

**Comment by YES-Lee** [comment]
你好，我非常喜欢这个主题，看了一下源码组织的也非常好，想学习一下源码，有些问题需要请教一下。所以方便给个联系方式吗？或者建个交流群？

**Comment by YES-Lee** [comment]
你好，我非常喜欢这个主题，看了一下源码组织的也非常好，想学习一下源码，有些问题需要请教一下。所以方便给个联系方式吗？或者建个交流群？

**Comment by ikeq** [comment]
看起来很麻烦，等 star 人数到 300 再考虑吧😆

**Comment by ikeq** [comment]
Need to find a place.

**Comment by ikeq** [comment]
Found a place finally, [#faq](https://github.com/ikeq/hexo-theme-inside#faq).
