### ISSUE TITLE
How to install ?

### ISSUE THREAD

**Issue by sgorki** [ikeq/hexo-theme-inside#93]
I downloaded release file,rename to inside and copy to my themes but it doesn't show anything
Site link: https://sharp-villani-dc8730.netlify.com/en/

**Comment by ike-c** [comment]
Please set the language to "en" or just remove that line.
All supported languages can be seen in `inside/languages` folder.

**Comment by sgorki** [comment]
now,it's show:"Failed to direct to /en"

**Comment by ike-c** [comment]
Your server forces a redirect to `/ en`.
